[package]
name = "rust_client"
version = "0.1.0"
edition = "2024"

[dependencies]
chiral-client = "0.1.0"
tonic = "0.11"
serde_json = "1"
anyhow = "1.0"

[build-dependencies]
tonic-build = "0.11"
prost-build = "0.12"

[package.metadata.dist]
dist = true